In [2]:
import numpy as np
import pandas as pd
import yaml
import requests

In [4]:
member = pd.read_parquet('../data/raw/member_details.parquet')

In [7]:
member.head(3).T

,0,1,2
bioguideId,W000832,B001328,G000607
birthYear,1987,1992,1981
currentMember,True,True,True
directOrderName,Aisha Wahab,Everton Blair Jr.,James Gallagher
district,14.0,13.0,1.0
firstName,Aisha,Everton,James
honorificName,Ms.,Mr.,Mr.
invertedOrderName,"Wahab, Aisha","Blair, Everton","Gallagher, James"
lastName,Wahab,Blair,Gallagher
officialWebsiteUrl,https://wahab.house.gov/,https://blair.house.gov/,https://gallagher.house.gov
partyHistory,"[{'partyAbbreviation': 'D', 'partyName': 'Demo...","[{'partyAbbreviation': 'D', 'partyName': 'Demo...","[{'partyAbbreviation': 'R', 'partyName': 'Repu..."
previousNames,"[{'directOrderName': 'Aisha Wahab', 'firstName...","[{'directOrderName': 'Everton Blair Jr.', 'fir...","[{'directOrderName': 'James Gallagher', 'first..."
state,California,Georgia,California
terms,"[{'chamber': 'House of Representatives', 'cong...","[{'chamber': 'House of Representatives', 'cong...","[{'chamber': 'House of Representatives', 'cong..."
updateDate,2026-09-29T07:40:27Z,2026-09-29T07:40:27Z,2026-09-29T07:40:27Z
addressInformation.city,Washington,Washington,Washington
addressInformation.district,DC,DC,DC
addressInformation.officeAddress,174 Cannon House Office Building,468 Cannon House Office Building,408 Cannon House Office Building
addressInformation.phoneNumber,(202) 225-5065,(202) 225-2939,(202) 225-3076
addressInformation.zipCode,20515.0,20515.0,20515.0
cosponsoredLegislation.count,2,21,57
cosponsoredLegislation.url,https://api.congress.gov/v3/member/W000832/cos...,https://api.congress.gov/v3/member/B001328/cos...,https://api.congress.gov/v3/member/G000607/cos...
depiction.attribution,Image courtesy of the Member,Image courtesy of the Member,NaN
depiction.imageUrl,https://www.congress.gov/img/member/6a986b632a...,https://www.congress.gov/img/member/6a9869d92a...,https://www.congress.gov/img/member/6a29d4f81c...
suffixName,NaN,Jr.,NaN
sponsoredLegislation.count,NaN,1.0,7.0
sponsoredLegislation.url,NaN,https://api.congress.gov/v3/member/B001328/spo...,https://api.congress.gov/v3/member/G000607/spo...
middleName,NaN,NaN,NaN
nickName,NaN,NaN,NaN
leadership,None,None,None
deathYear,NaN,NaN,NaN

In [10]:
voteview_url = 'https://voteview.com/static/data/out/members/HS119_members.csv'
ideology = pd.read_csv(voteview_url)
ideology.head(3).T

,0,1,2
congress,119,119,119
chamber,President,House,House
icpsr,99912,20301,21102
state_icpsr,99,41,41
district_code,0,3,7
state_abbrev,USA,AL,AL
party_code,200,200,100
occupancy,0.0,NaN,NaN
last_means,0.0,NaN,NaN
bioname,"TRUMP, Donald John","ROGERS, Mike Dennis","SEWELL, Terri"
bioguide_id,NaN,R000575,S001185
born,1946.0,1958.0,1965.0
died,NaN,NaN,NaN
nominate_dim1,0.403,0.379,-0.402
nominate_dim2,0.162,0.377,0.397
nominate_log_likelihood,NaN,-13.62663,-43.17652
nominate_geo_mean_probability,NaN,0.97596,0.92592
nominate_number_of_votes,NaN,560.0,561.0
nominate_number_of_errors,NaN,5.0,19.0
conditional,NaN,NaN,NaN
nokken_poole_dim1,NaN,0.398,-0.41
nokken_poole_dim2,NaN,0.396,0.452

In [18]:
## the not so equivalent - equivalent to a SQL join

## Five kinds of merge/join
## 1. Inner join: drop any row that has no match in the other dataset
## 2. Left join: keeps all rows in the first dataset listed, drops unmatched rows in the second
## 3. Right join: keeps all rows in the second dataset, drops unmatched rows in the first
## 4. Full/outer join: keeps all rows
## 5. Cross join: all pairwise combinations -- explodes your data

## Relationships
## L and R are my two datasets
## Fill in these sentences:
## "One row in L should match with A={one; many} row(s) in R"
## "One row in R should match with B={one; many} row(s) in L"
## This join is a B-to-A

## ex. L = committees, one row per committee
## R = committee membership, one row per member/committee assignment
## One row in committees should match with many rows in assignment
## One row in assignment should match to one row in committees

member_ideology = pd.merge(member, ideology,
                           left_on = 'bioguideId',
                           right_on = 'bioguide_id',
                           how = 'outer', ## the default is 'inner', but we recommend using outer / full join, will show us what matched and what failed to match
                           indicator = 'matched', ## new column to tell you what matched and what didn't
                           validate = 'one_to_many') ## run through the expectation in 'Relationships' above

In [19]:
ideology['bioguide_id'].value_counts()

bioguide_id
K000401    2
R000575    1
S001185    1
P000609    1
M001212    1
          ..
J000312    1
B001230    1
J000293    1
L000571    1
B001261    1
Name: count, Length: 555, dtype: int64

In [20]:
ideology.query("bioguide_id == 'K000401'").T

                                         60            78
congress                                119           119
chamber                               House         House
icpsr                                 22336         92336
state_icpsr                              71            71
district_code                             3             3
state_abbrev                             CA            CA
party_code                              200           328
occupancy                               NaN           NaN
last_means                              NaN           NaN
bioname                        KILEY, Kevin  KILEY, Kevin
bioguide_id                         K000401       K000401
born                                 1985.0        1985.0
died                                    NaN           NaN
nominate_dim1                         0.253         0.152
nominate_dim2                         0.418         0.357
nominate_log_likelihood           -24.96588     -39.94142
nominate_geo_mean_probability       0.93737       0.80295
nominate_number_of_votes              386.0         182.0
nominate_number_of_errors               8.0          15.0
conditional                             NaN           NaN
nokken_poole_dim1                      0.26         0.152
nokken_poole_dim2                     0.306         0.355

In [21]:
member_ideology['matched'].value_counts()

matched
both          556
right_only      1
left_only       0
Name: count, dtype: int64

In [23]:
member_ideology.query("matched == 'right_only'").T

                                                 556
bioguideId                                       NaN
birthYear                                        NaN
currentMember                                    NaN
directOrderName                                  NaN
district                                         NaN
firstName                                        NaN
honorificName                                    NaN
invertedOrderName                                NaN
lastName                                         NaN
officialWebsiteUrl                               NaN
partyHistory                                     NaN
previousNames                                    NaN
state                                            NaN
terms                                            NaN
updateDate                                       NaN
addressInformation.city                          NaN
addressInformation.district                      NaN
addressInformation.officeAddress                 NaN
addressInformation.phoneNumber                   NaN
addressInformation.zipCode                       NaN
cosponsoredLegislation.count                     NaN
cosponsoredLegislation.url                       NaN
depiction.attribution                            NaN
depiction.imageUrl                               NaN
suffixName                                       NaN
sponsoredLegislation.count                       NaN
sponsoredLegislation.url                         NaN
middleName                                       NaN
nickName                                         NaN
leadership                                       NaN
deathYear                                        NaN
congress                                         119
chamber                                    President
icpsr                                          99912
state_icpsr                                       99
district_code                                      0
state_abbrev                                     USA
party_code                                       200
occupancy                                        0.0
last_means                                       0.0
bioname                           TRUMP, Donald John
bioguide_id                                      NaN
born                                          1946.0
died                                             NaN
nominate_dim1                                  0.403
nominate_dim2                                  0.162
nominate_log_likelihood                          NaN
nominate_geo_mean_probability                    NaN
nominate_number_of_votes                         NaN
nominate_number_of_errors                        NaN
conditional                                      NaN
nokken_poole_dim1                                NaN
nokken_poole_dim2                                NaN
matched                                   right_only

In [24]:
member_ideology = member_ideology.query("bioname != 'TRUMP, Donald John'")

In [ ]:
member_ideology['matched'].value_counts()

matched
both          556
left_only       0
right_only      0
Name: count, dtype: int64

In [26]:
member_ideology = member_ideology.drop('matched', axis=1)

In [31]:
yaml_url = 'https://github.com/unitedstates/congress-legislators/blob/main/legislators-current.yaml?raw=True'
r = requests.get(yaml_url)
r

In [34]:
yaml.safe_load(r.text)

[{'id': {'bioguide': 'C000127',
   'thomas': '00172',
   'lis': 'S275',
   'govtrack': 300018,
   'opensecrets': 'N00007836',
   'votesmart': 27122,
   'fec': ['S8WA00194', 'H2WA01054'],
   'cspan': 26137,
   'wikipedia': 'Maria Cantwell',
   'house_history': 10608,
   'ballotpedia': 'Maria Cantwell',
   'maplight': 544,
   'icpsr': 39310,
   'wikidata': 'Q22250',
   'google_entity_id': 'kg:/m/01x68t',
   'pictorial': 13398},
  'name': {'first': 'Maria',
   'last': 'Cantwell',
   'official_full': 'Maria Cantwell'},
  'bio': {'birthday': '1958-10-13', 'gender': 'F'},
  'terms': [{'type': 'rep',
    'start': '1993-01-05',
    'end': '1995-01-03',
    'state': 'WA',
    'district': 1,
    'party': 'Democrat'},
   {'type': 'sen',
    'start': '2001-01-03',
    'end': '2007-01-03',
    'state': 'WA',
    'class': 1,
    'party': 'Democrat',
    'url': 'http://cantwell.senate.gov'},
   {'type': 'sen',
    'start': '2007-01-04',
    'end': '2013-01-03',
    'state': 'WA',
    'class': 1,
    'party': 'Democrat',
    'url': 'http://cantwell.senate.gov',
    'address': '311 HART SENATE OFFICE BUILDING WASHINGTON DC 20510',
    'phone': '202-224-3441',
    'fax': '202-228-0514',
    'contact_form': 'http://www.cantwell.senate.gov/contact/',
    'office': '311 Hart Senate Office Building'},
   {'type': 'sen',
    'start': '2013-01-03',
    'end': '2019-01-03',
    'state': 'WA',
    'party': 'Democrat',
    'class': 1,
    'url': 'https://www.cantwell.senate.gov',
    'address': '511 Hart Senate Office Building Washington DC 20510',
    'phone': '202-224-3441',
    'fax': '202-228-0514',
    'contact_form': 'http://www.cantwell.senate.gov/public/index.cfm/email-maria',
    'office': '511 Hart Senate Office Building',
    'state_rank': 'junior',
    'rss_url': 'http://www.cantwell.senate.gov/public/index.cfm/rss/feed'},
   {'type': 'sen',
    'start': '2019-01-03',
    'end': '2025-01-03',
    'state': 'WA',
    'class': 1,
    'party': 'Democrat',
    'state_rank': 'junior',
    'url': 'https://www.cantwell.senate.gov',
    'rss_url': 'http://www.cantwell.senate.gov/public/index.cfm/rss/feed',
    'contact_form': 'https://www.cantwell.senate.gov/public/index.cfm/email-maria',
    'address': '511 Hart Senate Office Building Washington DC 20510',
    'office': '511 Hart Senate Office Building',
    'phone': '202-224-3441'},
   {'type': 'sen',
    'start': '2025-01-03',
    'end': '2031-01-03',
    'state': 'WA',
    'class': 1,
    'state_rank': 'junior',
    'party': 'Democrat',
    'url': 'https://www.cantwell.senate.gov',
    'rss_url': 'http://www.cantwell.senate.gov/public/index.cfm/rss/feed',
    'contact_form': 'https://www.cantwell.senate.gov/public/index.cfm/email-maria',
    'address': '511 Hart Senate Office Building Washington DC 20510',
    'office': '511 Hart Senate Office Building',
    'phone': '202-224-3441'}]},
 {'id': {'bioguide': 'K000367',
   'thomas': '01826',
   'lis': 'S311',
   'govtrack': 412242,
   'opensecrets': 'N00027500',
   'votesmart': 65092,
   'fec': ['S6MN00267'],
   'cspan': 83701,
   'wikipedia': 'Amy Klobuchar',
   'house_history': 16558,
   'ballotpedia': 'Amy Klobuchar',
   'maplight': 724,
   'icpsr': 40700,
   'wikidata': 'Q22237',
   'google_entity_id': 'kg:/m/05fbpt',
   'pictorial': 13431},
  'name': {'first': 'Amy',
   'middle': 'Jean',
   'last': 'Klobuchar',
   'official_full': 'Amy Klobuchar'},
  'bio': {'birthday': '1960-05-25', 'gender': 'F'},
  'leadership_roles': [{'title': 'Senate Democratic Steering Committee Chair',
    'chamber': 'senate',
    'start': '2019-01-03',
    'end': '2021-01-03'},
   {'title': 'Senate Democratic Steering Committee Chair',
    'chamber': 'senate',
    'start': '2021-01-03',
    'end': '2023-01-03'},
   {'title': 'Senate Democratic Steering Committee Chair',
    'chamber': 'senate',
    'start': '2023-01-03',
    'end': '2025-01-03'},
   {'title': 'Senate Democratic Steering Committee Chair',
    'chamber': 'senate',
    'start': '2025-01-03'}],
  'terms': [{'type': 'sen',
    'start': '2007-01-04',
    'end': '2013-01-03',
    'state': 'MN',
    'class': 1,
    'party': 'Democrat',
    'url': 'http://klobuchar.senate.gov/',
    'address': '302 HART SENATE OFFICE BUILDING WASHINGTON DC 20510',
    'phone': '202-224-3244',
    'fax': '202-228-2186',
    'contact_form': 'http://www.klobuchar.senate.gov/emailamy.cfm',
    'office': '302 Hart Senate Office Building'},
   {'type': 'sen',
    'start': '2013-01-03',
    'end': '2019-01-03',
    'state': 'MN',
    'party': 'Democrat',
    'class': 1,
    'url': 'https://www.klobuchar.senate.gov',
    'address': '302 Hart Senate Office Building Washington DC 20510',
    'phone': '202-224-3244',
    'fax': '202-228-2186',
    'contact_form': 'http://www.klobuchar.senate.gov/public/index.cfm/contact',
    'office': '302 Hart Senate Office Building',
    'state_rank': 'senior'},
   {'type': 'sen',
    'start': '2019-01-03',
    'end': '2025-01-03',
    'state': 'MN',
    'class': 1,
    'party': 'Democrat',
    'state_rank': 'senior',
    'url': 'https://www.klobuchar.senate.gov',
    'contact_form': 'https://www.klobuchar.senate.gov/public/index.cfm/contact',
    'address': '425 Dirksen Senate Office Building Washington DC 20510',
    'office': '425 Dirksen Senate Office Building',
    'phone': '202-224-3244'},
   {'type': 'sen',
    'start': '2025-01-03',
    'end': '2031-01-03',
    'state': 'MN',
    'class': 1,
    'state_rank': 'senior',
    'party': 'Democrat',
    'url': 'https://www.klobuchar.senate.gov',
    'contact_form': 'https://www.klobuchar.senate.gov/public/index.cfm/contact',
    'address': '425 Dirksen Senate Office Building Washington DC 20510',
    'office': '425 Dirksen Senate Office Building',
    'phone': '202-224-3244'}]},
 {'id': {'bioguide': 'S000033',
   'thomas': '01010',
   'lis': 'S313',
   'govtrack': 400357,
   'opensecrets': 'N00000528',
   'votesmart': 27110,
   'fec': ['H8VT01016', 'S4VT00033'],
   'cspan': 994,
   'wikipedia': 'Bernie Sanders',
   'ballotpedia': 'Bernie Sanders',
   'maplight': 450,
   'icpsr': 29147,
   'house_history': 21173,
   'wikidata': 'Q359442',
   'google_entity_id': 'kg:/m/01_gbv',
   'pictorial': 13382},
  'name': {'first': 'Bernard',
   'last': 'Sanders',
   'nickname': 'Bernie',
   'official_full': 'Bernard Sanders'},
  'bio': {'birthday': '1941-09-08', 'gender': 'M'},
  'leadership_roles': [{'title': 'Senate Democratic Outreach Chair',
    'chamber': 'senate',
    'start': '2023-01-03',
    'end': '2025-01-03'},
   {'title': 'Senate Democratic Outreach Chair',
    'chamber': 'senate',
    'start': '2025-01-03'}],
  'terms': [{'type': 'rep',
    'start': '1991-01-03',
    'end': '1993-01-03',
    'state': 'VT',
    'district': 0,
    'party': 'Independent',
    'caucus': 'Democrat'},
   {'type': 'rep',
    'start': '1993-01-05',
    'end': '1995-01-03',
    'state': 'VT',
    'district': 0,
    'party': 'Independent',
    'caucus': 'Democrat'},
   {'type': 'rep',
    'start': '1995-01-04',
    'end': '1997-01-03',
    'state': 'VT',
    'district': 0,
    'party': 'Independent',
    'caucus': 'Democrat'},
   {'type': 'rep',
    'start': '1997-01-07',
    'end': '1999-01-03',
    'state': 'VT',
    'district': 0,
    'party': 'Independent',
    'caucus': 'Democrat'},
   {'type': 'rep',
    'start': '1999-01-06',
    'end': '2001-01-03',
    'state': 'VT',
    'district': 0,
    'party': 'Independent',
    'caucus': 'Democrat'},
   {'type': 'rep',
    'start': '2001-01-03',
    'end': '2003-01-03',
    'state': 'VT',
    'district': 0,
    'party': 'Independent',
    'caucus': 'Democrat'},
   {'type': 'rep',
    'start': '2003-01-07',
    'end': '2005-01-03',
    'state': 'VT',
    'district': 0,
    'party': 'Independent',
    'caucus': 'Democrat',
    'url': 'http://bernie.house.gov'},
   {'type': 'rep',
    'start': '2005-01-04',
    'end': '2007-01-03',
    'state': 'VT',
    'district': 0,
    'party': 'Independent',
    'caucus': 'Democrat',
    'url': 'http://bernie.house.gov'},
   {'type': 'sen',
    'start': '2007-01-04',
    'end': '2013-01-03',
    'state': 'VT',
    'class': 1,
    'party': 'Independent',
    'caucus': 'Democrat',
    'url': 'http://sanders.senate.gov/',
    'address': '332 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510',
    'phone': '202-224-5141',
    'fax': '202-228-0776',
    'contact_form': 'http://www.sanders.senate.gov/contact/',
    'office': '332 Dirksen Senate Office Building'},
   {'type': 'sen',
    'start': '2013-01-03',
    'end': '2019-01-03',
    'state': 'VT',
    'party': 'Independent',
    'caucus': 'Democrat',
    'class': 1,
    'url': 'https://www.sanders.senate.gov',
    'address': '332 Dirksen Senate Office Building Washington DC 20510',
    'phone': '202-224-5141',
    'fax': '202-228-0776',
    'contact_form': 'http://www.sanders.senate.gov/contact/',
    'office': '332 Dirksen Senate Office Building',
    'state_rank': 'junior',
    'rss_url': 'http://www.sanders.senate.gov/rss/'},
   {'type': 'sen',
    'start': '2019-01-03',
    'end': '2025-01-03',
    'state': 'VT',
    'class': 1,
    'party': 'Independent',
    'caucus': 'Democrat',
    'state_rank': 'senior',
    'url': 'https://www.sanders.senate.gov',
    'rss_url': 'http://www.sanders.senate.gov/rss/',
    'contact_form': 'https://www.sanders.senate.gov/contact/',
    'address': '332 Dirksen Senate Office Building Washington DC 20510',
    'office': '332 Dirksen Senate Office Building',
    'phone': '202-224-5141'},
   {'type': 'sen',
    'start': '2025-01-03',
    'end': '2031-01-03',
    'state': 'VT',
    'class': 1,
    'state_rank': 'senior',
    'party': 'Independent',
    'caucus': 'Democrat',
    'url': 'https://www.sanders.senate.gov',
    'rss_url': 'http://www.sanders.senate.gov/rss/',
    'contact_form': 'https://www.sanders.senate.gov/contact/',
    'address': '332 Dirksen Senate Office Building Washington DC 20510',
    'office': '332 Dirksen Senate Office Building',
    'phone': '202-224-5141'}]},
 {'id': {'bioguide': 'W000802',
   'thomas': '01823',
   'lis': 'S316',
   'govtrack': 412247,
   'opensecrets': 'N00027533',
   'votesmart': 2572,
   'fec': ['S6RI00221'],
   'cspan': 92235,
   'wikipedia': 'Sheldon Whitehouse',
   'ballotpedia': 'Sheldon Whitehouse',
   'maplight': 728,
   'icpsr': 40704,
   'wikidata': 'Q652066',
   'google_entity_id': 'kg:/m/07qw94',
   'pictorial': 13372},
  'name': {'first': 'Sheldon',
   'last': 'Whitehouse',
   'official_full': 'Sheldon Whitehouse'},
  'bio': {'gender': 'M', 'birthday': '1955-10-20'},
  'terms': [{'type': 'sen',
    'start': '2007-01-04',
    'end': '2013-01-03',
    'state': 'RI',
    'class': 1,
    'party': 'Democrat',
    'url': 'http://whitehouse.senate.gov/',
    'address': '717 HART SENATE OFFICE BUILDING WASHINGTON DC 20510',
    'phone': '202-224-2921',
    'fax': '202-228-6362',
    'contact_form': 'http://www.whitehouse.senate.gov/contact/',
    'office': '717 Hart Senate Office Building'},
   {'type': 'sen',
    'start': '2013-01-03',
    'end': '2019-01-03',
    'state': 'RI',
    'party': 'Democrat',
    'class': 1,
    'url': 'https://www.whitehouse.senate.gov',
    'address': '530 Hart Senate Office Building Washington DC 20510',
    'phone': '202-224-2921',
    'fax': '202-228-6362',
    'contact_form': 'https://www.whitehouse.senate.gov/contact/email-sheldon',
    'office': '530 Hart Senate Office Building',
    'state_rank': 'junior',
    'rss_url': 'http://www.whitehouse.senate.gov/rss/feeds/?type=all&amp;cachebuster=1'},
   {'type': 'sen',
    'start': '2019-01-03',
    'end': '2025-01-03',
    'state': 'RI',
    'class': 1,
    'party': 'Democrat',
    'state_rank': 'junior',
    'url': 'https://www.whitehouse.senate.gov',
    'rss_url': 'http://www.whitehouse.senate.gov/rss/feeds/?type=all&amp;cachebuster=1',
    'contact_form': 'https://www.whitehouse.senate.gov/contact/email-sheldon',
    'address': '530 Hart Senate Office Building Washington DC 20510',
    'office': '530 Hart Senate Office Building',
    'phone': '202-224-2921'},
   {'type': 'sen',
    'start': '2025-01-03',
    'end': '2031-01-03',
    'state': 'RI',
    'class': 1,
    'state_rank': 'junior',
    'party': 'Democrat',
    'url': 'https://www.whitehouse.senate.gov',
    'rss_url': 'http://www.whitehouse.senate.gov/rss/feeds/?type=all&amp;cachebuster=1',
    'contact_form': 'https://www.whitehouse.senate.gov/contact/email-sheldon',
    'address': '530 Hart Senate Office Building Washington DC 20510',
    'office': '530 Hart Senate Office Building',
    'phone': '202-224-2921'}]},
 {'id': {'bioguide': 'B001261',
   'thomas': '01881',
   'lis': 'S317',
   'govtrack': 412251,
   'opensecrets': 'N00006236',
   'votesmart': 52662,
   'fec': ['S6WY00068'],
   'cspan': 1024777,
   'wikipedia': 'John Barrasso',
   'ballotpedia': 'John Barrasso',
   'maplight': 732,
   'icpsr': 40707,
   'wikidata': 'Q720521',
   'google_entity_id': 'kg:/m/02rsm32',
   'pictorial': 13410},
  'name': {'first': 'John',
   'middle': 'A.',
   'last': 'Barrasso',
   'official_full': 'John Barrasso'},
  'bio': {'birthday': '1952-07-21', 'gender': 'M'},
  'leadership_roles': [{'title': 'Senate Republican Conference Chair',
    'chamber': 'senate',
    'start': '2019-01-03',
    'end': '2021-01-03'},
   {'title': 'Senate Republican Conference Chair',
    'chamber': 'senate',
    'start': '2021-01-03',
    'end': '2023-01-03'},
   {'title': 'Senate Republican Conference Chair',
    'chamber': 'senate',
    'start': '2023-01-03',
    'end': '2025-01-03'},
   {'title': 'Senate Majority Whip',
    'chamber': 'senate',
    'start': '2025-01-03'}],
  'terms': [{'type': 'sen',
    'start': '2007-06-25',
    'end': '2013-01-03',
    'state': 'WY',
    'class': 1,
    'party': 'Republican',
    'url': 'http://barrasso.senate.gov',
    'address': '307 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510',
    'phone': '202-224-6441',
    'fax': '202-224-1724',
    'contact_form': 'http://www.barrasso.senate.gov/public/index.cfm?FuseAction=ContactUs.ContactForm',
    'office': '307 Dirksen Senate Office Building',
    'how': 'appointment'},
   {'type': 'sen',
    'start': '2013-01-03',
    'end': '2019-01-03',
    'state': 'WY',
    'party': 'Republican',
    'class': 1,
    'url': 'https://www.barrasso.senate.gov',
    'address': '307 Dirksen Senate Office Building Washington DC 20510',
    'phone': '202-224-6441',
    'fax': '202-224-1724',
    'contact_form': 'https://www.barrasso.senate.gov/public/index.cfm/contact-form',
    'office': '307 Dirksen Senate Office Building',
    'state_rank': 'junior',
    'rss_url': 'http://www.barrasso.senate.gov/public/index.cfm?FuseAction=Rss.Feed'},
   {'type': 'sen',
    'start': '2019-01-03',
    'end': '2025-01-03',
    'state': 'WY',
    'class': 1,
    'party': 'Republican',
    'state_rank': 'senior',
    'url': 'https://www.barrasso.senate.gov',
    'rss_url': 'http://www.barrasso.senate.gov/public/index.cfm?FuseAction=Rss.Feed',
    'contact_form': 'https://www.barrasso.senate.gov/public/index.cfm/contact-form',
    'address': '307 Dirksen Senate Office Building Washington DC 20510',
    'office': '307 Dirksen Senate Office Building',
    'phone': '202-224-6441'},
   {'type': 'sen',
    'start': '2025-01-03',
    'end': '2031-01-03',
    'state': 'WY',
    'class': 1,
    'state_rank': 'senior',
    'party': 'Republican',
    'url': 'https://www.barrasso.senate.gov',
    'rss_url': 'http://www.barrasso.senate.gov/public/index.cfm?FuseAction=Rss.Feed',
    'contact_form': 'https://www.barrasso.senate.gov/public/index.cfm/contact-form',
    'address': '307 Dirksen Senate Office Building Washington DC 20510',
    'office': '307 Dirksen Senate Office Building',
    'phone': '202-224-6441'}]},
 {'id': {'bioguide': 'W000437',
   'thomas': '01226',
   'lis': 'S318',
   'govtrack': 400432,
   'opensecrets': 'N00003280',
   'votesmart': 21926,
   'fec': ['H4MS01078', 'S8MS00196'],
   'cspan': 18203,
   'wikipedia': 'Roger Wicker',
   'ballotpedia': 'Roger Wicker',
   'maplight': 517,
   'icpsr': 29534,
   'house_history': 23734,
   'wikidata': 'Q390491',
   'google_entity_id': 'kg:/m/025xxb',
   'pictorial': 13373},
  'name': {'first': 'Roger',
   'middle': 'F.',
   'last': 'Wicker',
   'official_full': 'Roger F. Wicker'},
  'bio': {'birthday': '1951-07-05', 'gender': 'M'},
  'terms': [{'type': 'rep',
    'start': '1995-01-04',
    'end': '1997-01-03',
    'state': 'MS',
    'district': 1,
    'party': 'Republican'},
   {'type': 'rep',
    'start': '1997-01-07',
    'end': '1999-01-03',
    'state': 'MS',
    'district': 1,
    'party': 'Republican'},
   {'type': 'rep',
    'start': '1999-01-06',
    'end': '2001-01-03',
    'state': 'MS',
    'district': 1,
    'party': 'Republican'},
   {'type': 'rep',
    'start': '2001-01-03',
    'end': '2003-01-03',
    'state': 'MS',
    'district': 1,
    'party': 'Republican'},
   {'type': 'rep',
    'start': '2003-01-07',
    'end': '2005-01-03',
    'state': 'MS',
    'district': 1,
    'party': 'Republican',
    'url': 'http://www.house.gov/wicker'},
   {'type': 'rep',
    'start': '2005-01-04',
    'end': '2007-01-03',
    'state': 'MS',
    'district': 1,
    'party': 'Republican',
    'url': 'http://www.house.gov/wicker'},
   {'type': 'rep',
    'start': '2007-01-04',
    'end': '2007-12-31',
    'state': 'MS',
    'district': 1,
    'party': 'Republican',
    'url': 'http://www.house.gov/wicker'},
   {'type': 'sen',
    'start': '2007-12-31',
    'end': '2013-01-03',
    'state': 'MS',
    'class': 1,
    'party': 'Republican',
    'url': 'http://wicker.senate.gov',
    'address': '555 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510',
    'phone': '202-224-6253',
    'fax': '202-228-0378',
    'contact_form': 'http://www.wicker.senate.gov/public/index.cfm?FuseAction=Contact.EMailSenatorWicker',
    'office': '555 Dirksen Senate Office Building',
    'how': 'appointment'},
   {'type': 'sen',
    'start': '2013-01-03',
    'end': '2019-01-03',
    'state': 'MS',
    'party': 'Republican',
    'class': 1,
    'url': 'https://www.wicker.senate.gov',
    'address': '555 Dirksen Senate Office Building Washington DC 20510',
    'phone': '202-224-6253',
    'fax': '202-228-0378',
    'contact_form': 'https://www.wicker.senate.gov/public/index.cfm/contact',
    'office': '555 Dirksen Senate Office Building',
    'state_rank': 'senior'},
   {'type': 'sen',
    'start': '2019-01-03',
    'end': '2025-01-03',
    'state': 'MS',
    'class': 1,
    'party': 'Republican',
    'state_rank': 'senior',
    'url': 'https://www.wicker.senate.gov',
    'contact_form': 'https://www.wicker.senate.gov/public/index.cfm/contact',
    'address': '425 Russell Senate Office Building Washington DC 20510',
    'office': '425 Russell Senate Office Building',
    'phone': '202-224-6253'},
   {'type': 'sen',
    'start': '2025-01-03',
    'end': '2031-01-03',
    'state': 'MS',
    'class': 1,
    'state_rank': 'senior',
    'party': 'Republican',
    'url': 'https://www.wicker.senate.gov',
    'contact_form': 'https://www.wicker.senate.gov/public/index.cfm/contact',
    'address': '425 Russell Senate Office Building Washington DC 20510',
    'office': '425 Russell Senate Office Building',
    'phone': '202-224-6253'}]},
 {'id': {'bioguide': 'C001035',
   'thomas': '01541',
   'lis': 'S252',
   'govtrack': 300025,
   'opensecrets': 'N00000491',
   'votesmart': 379,
   'fec': ['S6ME00159'],
   'cspan': 45738,
   'wikipedia': 'Susan Collins',
   'house_history': 11742,
   'ballotpedia': 'Susan Collins',
   'maplight': 551,
   'icpsr': 49703,
   'wikidata': 'Q22279',
   'google_entity_id': 'kg:/m/020y8m',
   'pictorial': 13395},
  'name': {'first': 'Susan',
   'middle': 'M.',
   'last': 'Collins',
   'official_full': 'Susan M. Collins'},
  'bio': {'birthday': '1952-12-07', 'gender': 'F'},
  'terms': [{'type': 'sen',
    'start': '1997-01-07',
    'end': '2003-01-03',
    'state': 'ME',
    'class': 2,
    'party': 'Republican'},
   {'type': 'sen',